//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCos5CSPGatewayED {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EDResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EDResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iCos5CSPGatewayED.EDResources", typeof(EDResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   - CSP Gateway ver1.7
        ///1. BEMS 업로드 기능 추가
        ///2. 프로그램 Title 수정(CSP Gateway -&gt; Cloud Gateway)
        ///
        ///- CSP Gateway ver1.6
        ///1. Inbase 업로드 기능 추가
        ///2. Insite, Inbase 서비스 설정 가능
        ///
        ///- CSP Gateway ver1.5 Hotfix 수정사항
        ///1. 제어 비활성화 시 Insite 제어 DB 비우기 시간 설정 추가
        ///
        ///- CSP Gateway ver1.4 Hotfix 수정사항
        ///1. S3 Bucket upload 예외 발생시 교착상태 수정
        ///2. 정보에 Release Notes 보기 추가
        ///
        ///- CSP Gateway ver1.3 Hotfix 수정사항
        ///1. 하한값 알람 오류 수정(원인 : 하한값만 있는 경우 상한값 기준값이 없어서 예외 발생 -&gt; 기준값이 없는 경우 무시하는 것으로 변경)
        ///2. Modbus Tag 간헐적 비정상적 값 입력(원인 : 드라이버에서 값 처리 중 로딩하는 경우 등 동[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReleaseNotes {
            get {
                return ResourceManager.GetString("ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] RuntimeAddins {
            get {
                object obj = ResourceManager.GetObject("RuntimeAddins", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
